"""Typed domain contracts shared by all labs and services."""

from .enums import ProductType, UsageType, WorkflowState
from .models import (
    ComparisonResult,
    CustomerRequirement,
    DocumentChunk,
    DocumentSearchRequest,
    DocumentSearchResult,
    MissingInformation,
    Product,
    ProductCandidate,
    ProductFilter,
    ProductSearchRequest,
    ProductSearchResult,
    Proposal,
    ProposalOption,
    SizingRequest,
    SizingResult,
    ToolResult,
    ValidationFailure,
    ValidationResult,
    WorkflowContext,
)

__all__ = [
    "ComparisonResult",
    "CustomerRequirement",
    "DocumentChunk",
    "DocumentSearchRequest",
    "DocumentSearchResult",
    "MissingInformation",
    "Product",
    "ProductCandidate",
    "ProductFilter",
    "ProductSearchRequest",
    "ProductSearchResult",
    "Proposal",
    "ProposalOption",
    "ProductType",
    "SizingRequest",
    "SizingResult",
    "ToolResult",
    "UsageType",
    "ValidationFailure",
    "ValidationResult",
    "WorkflowContext",
    "WorkflowState",
]
