CREATE TABLE IF NOT EXISTS products (
    id VARCHAR(64) PRIMARY KEY,
    catalog_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    sku VARCHAR(100),
    name TEXT NOT NULL,
    manufacturer VARCHAR(100),
    product_type VARCHAR(50) NOT NULL DEFAULT 'ai_workstation'
        CHECK (product_type IN ('ai_workstation', 'ai_server', 'ai_pc')),
    platform VARCHAR(100),
    cpu_model TEXT,
    cpu_options JSONB NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(cpu_options) = 'array'),
    gpu_vendor VARCHAR(50),
    gpu_model TEXT,
    gpu_count INTEGER CHECK (gpu_count IS NULL OR gpu_count > 0),
    gpu_vram_per_gpu_gb NUMERIC(10,2)
        CHECK (gpu_vram_per_gpu_gb IS NULL OR gpu_vram_per_gpu_gb > 0),
    total_gpu_vram_gb NUMERIC(10,2)
        CHECK (total_gpu_vram_gb IS NULL OR total_gpu_vram_gb > 0),
    max_gpu_slots INTEGER CHECK (max_gpu_slots IS NULL OR max_gpu_slots > 0),
    installed_ram_gb INTEGER CHECK (installed_ram_gb IS NULL OR installed_ram_gb > 0),
    max_ram_gb INTEGER CHECK (max_ram_gb IS NULL OR max_ram_gb > 0),
    installed_storage_gb INTEGER
        CHECK (installed_storage_gb IS NULL OR installed_storage_gb > 0),
    max_storage_gb INTEGER CHECK (max_storage_gb IS NULL OR max_storage_gb > 0),
    storage_slots INTEGER CHECK (storage_slots IS NULL OR storage_slots > 0),
    power_w INTEGER CHECK (power_w IS NULL OR power_w > 0),
    form_factor VARCHAR(100),
    base_price_vnd BIGINT CHECK (base_price_vnd IS NULL OR base_price_vnd >= 0),
    listed_price_vnd BIGINT CHECK (listed_price_vnd IS NULL OR listed_price_vnd >= 0),
    base_price_includes JSONB NOT NULL DEFAULT '["chassis"]'::jsonb
        CHECK (jsonb_typeof(base_price_includes) = 'array'),
    availability VARCHAR(30) NOT NULL DEFAULT 'unknown'
        CHECK (availability IN ('in_stock', 'out_of_stock', 'preorder', 'contact', 'unknown')),
    source_url TEXT NOT NULL,
    source_urls JSONB NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(source_urls) = 'array'),
    source_retrieved_at TIMESTAMPTZ,
    specs JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(specs) = 'object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (installed_ram_gb IS NULL OR max_ram_gb IS NULL
           OR max_ram_gb >= installed_ram_gb),
    CHECK (installed_storage_gb IS NULL OR max_storage_gb IS NULL
           OR max_storage_gb >= installed_storage_gb),
    CHECK (gpu_count IS NULL OR max_gpu_slots IS NULL
           OR max_gpu_slots >= gpu_count)
);

CREATE INDEX IF NOT EXISTS idx_products_price ON products(base_price_vnd);
CREATE INDEX IF NOT EXISTS idx_products_listed_price ON products(listed_price_vnd);
CREATE INDEX IF NOT EXISTS idx_products_total_gpu_vram ON products(total_gpu_vram_gb);
CREATE INDEX IF NOT EXISTS idx_products_installed_ram ON products(installed_ram_gb);
CREATE INDEX IF NOT EXISTS idx_products_max_ram ON products(max_ram_gb);
CREATE INDEX IF NOT EXISTS idx_products_max_gpu_slots ON products(max_gpu_slots);
CREATE INDEX IF NOT EXISTS idx_products_gpu_vendor ON products(gpu_vendor);
CREATE INDEX IF NOT EXISTS idx_products_availability ON products(availability);
CREATE INDEX IF NOT EXISTS idx_products_product_type ON products(product_type);
