CREATE TABLE IF NOT EXISTS product_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(64) NOT NULL,
    knowledge_base_id TEXT NOT NULL,
    knowledge_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    source_url TEXT,
    content_sha256 TEXT,
    provider_parse_status VARCHAR(64) NOT NULL DEFAULT 'unknown',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT product_documents_product_id_fkey
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
    CONSTRAINT product_documents_provider_identity_unique
        UNIQUE (knowledge_base_id, knowledge_id),
    CONSTRAINT product_documents_nonblank_identity_check
        CHECK (
            length(btrim(knowledge_base_id)) > 0
            AND length(btrim(knowledge_id)) > 0
            AND length(btrim(filename)) > 0
            AND length(btrim(provider_parse_status)) BETWEEN 1 AND 64
        ),
    CONSTRAINT product_documents_source_url_check
        CHECK (source_url IS NULL OR source_url ~ '^https?://[^[:space:]]+$'),
    CONSTRAINT product_documents_sha256_check
        CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX IF NOT EXISTS idx_product_documents_product_id
    ON product_documents(product_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_documents_product_kb_sha256
    ON product_documents(product_id, knowledge_base_id, content_sha256)
    WHERE content_sha256 IS NOT NULL;
